### ISSUE TITLE
Github Actions連携して誰でもデプロイできるようにする

### ISSUE THREAD

**Issue by yunosuke924** [team-morning-six/DtoNApp#1]
誰でもデプロイできるように、github actionsでmainブランチにpush or mergeした瞬間にsam build → sam deployが走るようにする(自動テストもここで実行される)

**Comment by yukiHaga** [comment]
こちら mainブランチにpush or マージしたらワークフロー(sam build → sam deploy)が自動で実行されるようになりましたー！
そのため、doneとさせていただきます。🙏

Actions → DtoN App deploy → Run workflowから手動で実行することもできますー！
